### ISSUE TITLE
Adding the initial parts of the model 

### ISSUE THREAD

**Issue by apprenticearnab** [apprenticearnab/ReinforceBots#2]

**Comment by apprenticearnab** [comment]
Implement the **Aggregating Word Vectors into Sentence Vectors** and **Aggregating Sentence Vectors into a Document Vector** module as mentioned in the <a href="https://drive.google.com/file/d/1htup9eBUCSfxyt6NHavnLZGShR1sAAOF/view?usp=sharing">paper</a> using the basic convolution , max-pool modules provided by Pytorch for raw texts . You can get more information regarding this modules from the documentation of <a href="https://pytorch.org/docs/stable/index.html">Pytorch</a>.

**Comment by nesarasr** [comment]
Can I work on this?
Also the linked paper in this issue seems to be in trash folder, could you update that? Thanks!

**Comment by apprenticearnab** [comment]
I have updated the link , please try to develop all the parts of the model . It will be very helpful if you develop the whole model using the concepts of OOP .
